#server:
#  port: 8084
#
spring:
  application:
    name: api-gateway
    
  config:
    import: optional:configserver:http://localhost:8888     
    
    
    
okta:
  oauth2:
    issuer: https://dev-94594400.okta.com/oauth2/default   
    audience: api://default
    client-id: 0oa946552yAWi4lR95d7
    client-secret: BkZQ7KQEWGz4Up_W7FRCjPG5zzMPwdktZMmOtFke
    scopes: openid, profile, email, offline_access
    
#  cloud:
#    gateway:
#      routes:
#      - id: USER-SERVICE
#        uri: lb://USER-SERVICE
#        predicates:
#          - Path=/user/**
#          
#      - id: HOTEL-SERVICE
#        uri: lb://HOTEL-SERVICE
#        predicates:
#          - Path=/hotel/**
#           
#      - id: RATING-SERVICE
#        uri: lb://RATING-SERVICE
#        predicates:
#          - Path=/rating/**
#      
#        