server:
  port: 8081
spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3307/userservice
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: root
  config:
    import: optional:configserver:http://localhost:8888
    
    
#  jpa:
#    hibernate:
#      ddl-auto: update  
  application:
    name: user-service


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"