server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akashshetty6/config-server-user-app
          clone-on-start: true
          
  application:
    name: config-server     
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"     